# Site settings
title: Ramón Pérez-Alonso, LMSW
description: "Copy Editing Business Website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: RPA.svg

# Hero
hero: 
    hero_img: 20190214_091147.jpg
    hero_title: "R. Pérez-Alonso, LMSW"
    hero_description: "Copy Editing, Proofreading, Academic Writing Advisement."

# Contact form
api_token: 766cb9bbe967659e3b27a6f70734e3ca # Enter API token here

# Contact info
contact:
#    phone: 932 50 540
#    emergency: 931 53 234
    email: R.Perez.Alonso.business@gmail.com
    mail:
        user: R.Perez.Alonso.business
        host: gmail.com
    address: Brest, <br> France

# Opening hours
monday_friday: 9:00 – 18:00
saturday: by appointement
response_time: within 48h
# Testimonials
testimonials:
    testimonials_img: parallax.jpg


# Instruction
instructions:
    instructions_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Brest, France
    address_details: RPA.svg

# Social settings
#facebook: http://facebook.com
#twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: © 2019 Ramón Pérez-Alonso - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
