- icon: icon-papers
  title:     Articles scientifiques
  description: >
    Travail éditorial et corrections pour présenter votre recherche de manière claire et concise tout en respectant les directives et les normes de publication de la revue scientifique pour laquelle vous allez écrire.
    
  pricing: 30 EU par 250 mots

- icon: icon-globe
  title:  Offres commerciales

  description: | 
    Que ce soit de la publicité, une plaquette, une proposition ou même un communiqué officiel de votre entreprise, je peux m’assurer que le message soit transmis le plus efficacement possible à votre marché ou au public que vous ciblez.
  pricing: 30 EU per 250 mots
  
- icon: icon-resume
  title: CV, Lettres de Motivation
  description: | 
    Je vous aide à générer un CV modulaire et/ou une lettre de motivation pour vous présenter comme le candidat idéal. 
  pricing: 30 EU par heure
  
- icon: icon-pen
  title: Projets universitaires
  description: | 
    Soumettez-moi le brouillon de votre travail en anglais avec l’énoncé . Nous pourrons soit procéder aux corrections à distance, soit en personne, et établir des stratégies de travail qui vous serviront pour vos projets futurs.
  pricing: 25 EU par heure (30 EU par heure pour travail urgent)
  
  
- icon: icon-tutoring2
  title: Cours Particuliers
  description: | 
    Je vous propose des ateliers individuels  pour améliorer vos compétences en conversation, en présentation ainsi que pour passer en revue les documents pour lesquels vous avez besoin d’aide.
  pricing: 30 EU par heure
